# Generated by Django 3.2.7 on 2021-09-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=56, unique=True)),
                ('asset1_code', models.CharField(max_length=12)),
                ('asset1_issuer', models.CharField(max_length=56)),
                ('asset2_code', models.CharField(max_length=12)),
                ('asset2_issuer', models.CharField(max_length=56)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
