# Generated by Django 3.2.9 on 2021-12-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketkeys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketkey',
            name='downvote_account_id',
            field=models.CharField(max_length=56, null=True, unique=True),
        ),
    ]
