# Generated by Django 3.2.9 on 2022-02-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketkeys', '0003_marketkey_is_auth_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('issuer', models.CharField(max_length=56)),
                ('is_banned', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['code', 'issuer'], name='marketkeys__code_ca41f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('code', 'issuer')},
        ),
        migrations.AddField(
            model_name='marketkey',
            name='asset1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='marketkeys.asset'),
        ),
        migrations.AddField(
            model_name='marketkey',
            name='asset2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='marketkeys.asset'),
        ),
    ]
