# Generated by Django 3.2.9 on 2022-02-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketkeys', '0004_auto_20220211_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketkey',
            name='asset1_code',
        ),
        migrations.RemoveField(
            model_name='marketkey',
            name='asset1_issuer',
        ),
        migrations.RemoveField(
            model_name='marketkey',
            name='asset2_code',
        ),
        migrations.RemoveField(
            model_name='marketkey',
            name='asset2_issuer',
        ),
        migrations.AlterField(
            model_name='marketkey',
            name='asset1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='marketkeys.asset'),
        ),
        migrations.AlterField(
            model_name='marketkey',
            name='asset2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='marketkeys.asset'),
        ),
    ]
