# Generated by Django 3.2.12 on 2022-02-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketkeys', '0005_auto_20220211_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('auth_req', 'Auth Required'), ('isolated', 'Isolated Market')], max_length=8)),
                ('status', models.CharField(choices=[('ban', 'Banned'), ('fixed', 'Fixed'), ('unban', 'Unbanned')], max_length=5)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('fixed_at', models.DateTimeField(null=True)),
                ('unbanned_at', models.DateTimeField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='marketkeys.asset')),
            ],
        ),
    ]
