# Generated by Django 3.2.12 on 2022-02-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketkeys', '0006_assetban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketkey',
            name='is_auth_required',
        ),
    ]
