# Generated by Django 3.2.12 on 2022-02-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketkeys', '0007_remove_marketkey_is_auth_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='voting_boost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='asset',
            name='voting_boost_cap',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
    ]
