# Generated by Django 3.2.23 on 2025-01-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketkeys', '0008_auto_20220218_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='voting_boost_cap',
        ),
        migrations.AlterField(
            model_name='assetban',
            name='reason',
            field=models.CharField(choices=[('auth_req', 'Auth Required'), ('auth_rev', 'Auth Revocable'), ('auth_cla', 'Auth Clawback Enabled'), ('isolated', 'Isolated Market')], max_length=8),
        ),
    ]
