# Generated by Django 3.2.23 on 2025-04-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketkeys', '0009_auto_20250116_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='downvote_immunity',
            field=models.BooleanField(default=False),
        ),
    ]
