# Generated by Django 3.2.25 on 2025-10-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketkeys', '0010_asset_downvote_immunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_whitelisted',
            field=models.BooleanField(default=False, help_text='Force allow asset even if there are reasons for ban. Mutually exclusive with is_banned'),
        ),
    ]
