# Generated by Django 3.2.25 on 2026-05-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketkeys', '0011_asset_is_whitelisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='is_banned',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='is_whitelisted',
        ),
        migrations.DeleteModel(
            name='AssetBan',
        ),
    ]
