# Generated by Django 3.2.25 on 2026-05-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketkeys', '0012_auto_20260520_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='in_asset_registry',
            field=models.BooleanField(default=False),
        ),
    ]
